services:
  register_book:
    build: ./microservice_register_book
    container_name: register_book 
    ports:
      - "4000:4000"

  list_book:
    build: ./microservice_list_book
    container_name: list_book
    ports:
      - "4001:4001"
  update_book:
    build: ./microservice_update_book
    container_name: update_book
    ports:
      - "4002:4002"
   
  remove_book:
    build: ./microservice_remove_book
    container_name: delete_book 
    ports:
      - "4003:4003"
   
  

