name: CI/CD - Docker Build & Deploy

on:
  push:
    branches:
      - QA

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      # Paso 2: Login a Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Step 3: Build and upload book_management images
      - name: Build and Push Book Management Microservices
        run: |
          for service in register update list remove; do
            echo "Building and pushing microservice_${service}_book..."
            docker build -f book_management/Microservice_${service}_book/Dockerfile -t ${{ secrets.DOCKER_USERNAME }}/microservice_${service}_book:latest book_management/Microservice_${service}_book
            docker push ${{ secrets.DOCKER_USERNAME }}/microservice_${service}_book:latest
          done

      # Step 4: Build and upload book_catalog images
      - name: Build and Push Book Catalog Microservices
        run: |
          for service in registre update list delete; do
            echo "Building and pushing microservice_${service}_catalog..."
            docker build -f book_catalog/Microservice_${service}_catalog/Dockerfile -t ${{ secrets.DOCKER_USERNAME }}/microservice_${service}_catalog:latest book_catalog/Microservice_${service}_catalog
            docker push ${{ secrets.DOCKER_USERNAME }}/microservice_${service}_catalog:latest
          done

      # Step 5: Build and upload reservations_management images
      - name: Build and Push Reservations Management Microservices
        run: |
          for service in register update list delete; do
            echo "Building and pushing microservice_${service}_reservation..."
            docker build -f reservation_management/Microservice_${service}_reservation/Dockerfile -t ${{ secrets.DOCKER_USERNAME }}/microservice_${service}_reservation:latest reservation_management/Microservice_${service}_reservation
            docker push ${{ secrets.DOCKER_USERNAME }}/microservice_${service}_reservation:latest
          done

      # Step 6: Build and upload users images
      - name: Build and Push Users Microservices
        run: |
          for service in register update list remove; do
            echo "Building and pushing microservice_${service}_user..."
            docker build -f users/Microservice_${service}_user/Dockerfile -t ${{ secrets.DOCKER_USERNAME }}/microservice_${service}_user:latest users/Microservice_${service}_user
            docker push ${{ secrets.DOCKER_USERNAME }}/microservice_${service}_user:latest
          done

  deploy-book-management:
    needs: build-and-push
    runs-on: ubuntu-latest
    steps:
      - name: SSH into EC2 Book Management and deploy containers
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ secrets.EC2_BOOK_IP }}
          username: ubuntu
          key: ${{ secrets.BOOK_KEY }}
          script: |
            if ! command -v docker &> /dev/null; then
              echo "Docker no está instalado. Instalando..."
              sudo apt update && sudo apt install -y docker.io
            fi
            sudo systemctl enable --now docker

            echo "Descargando imágenes..."
            sudo docker pull ${{ secrets.DOCKER_USERNAME }}/microservice_register_book:latest
            sudo docker pull ${{ secrets.DOCKER_USERNAME }}/microservice_update_book:latest
            sudo docker pull ${{ secrets.DOCKER_USERNAME }}/microservice_list_book:latest
            sudo docker pull ${{ secrets.DOCKER_USERNAME }}/microservice_remove_book:latest

            sudo docker stop microservice_register_book || true && sudo docker rm microservice_register_book || true
            sudo docker stop microservice_update_book || true && sudo docker rm microservice_update_book || true
            sudo docker stop microservice_list_book || true && sudo docker rm microservice_list_book || true
            sudo docker stop microservice_remove_book || true && sudo docker rm microservice_remove_book || true

            mkdir -p src
            echo "DB_HOST=${{ secrets.DB_HOST }}" > src/.env
            echo "DB_NAME=${{ secrets.DB_NAME }}" >> src/.env
            echo "DB_USER=${{ secrets.DB_USER }}" >> src/.env
            echo "DB_PASS=${{ secrets.DB_PASS }}" >> src/.env
            echo "DB_PORT=${{ secrets.DB_PORT }}" >> src/.env

            cat src/.env

            echo "Ejecutando microservicios book_management..."
            sudo docker run -d --name microservice_register_book --env-file src/.env -p 4000:4000 ${{ secrets.DOCKER_USERNAME }}/microservice_register_book:latest
            sudo docker run -d --name microservice_update_book --env-file src/.env -p 4003:4003 ${{ secrets.DOCKER_USERNAME }}/microservice_update_book:latest
            sudo docker run -d --name microservice_list_book --env-file src/.env -p 4001:4001 ${{ secrets.DOCKER_USERNAME }}/microservice_list_book:latest
            sudo docker run -d --name microservice_remove_book --env-file src/.env -p 4002:4002 ${{ secrets.DOCKER_USERNAME }}/microservice_remove_book:latest

            sudo docker ps -a
            echo "Deployment of book_management completed."

  deploy-book-catalog:
    needs: build-and-push
    runs-on: ubuntu-latest
    steps:
      - name: SSH into EC2 Book Catalog and deploy containers
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ secrets.EC2_CATALOG_IP }}
          username: ubuntu
          key: ${{ secrets.CATALOG_KEY }}
          script: |
            if ! command -v docker &> /dev/null; then
              echo "Docker no está instalado. Instalando..."
              sudo apt update && sudo apt install -y docker.io
            fi
            sudo systemctl enable --now docker

            echo "Descargando imágenes..."
            sudo docker pull ${{ secrets.DOCKER_USERNAME }}/microservice_registre_catalog:latest
            sudo docker pull ${{ secrets.DOCKER_USERNAME }}/microservice_update_catalog:latest
            sudo docker pull ${{ secrets.DOCKER_USERNAME }}/microservice_list_catalog:latest
            sudo docker pull ${{ secrets.DOCKER_USERNAME }}/microservice_delete_catalog:latest

            sudo docker stop microservice_registre_catalog || true && sudo docker rm microservice_registre_catalog || true
            sudo docker stop microservice_update_catalog || true && sudo docker rm microservice_update_catalog || true
            sudo docker stop microservice_list_catalog || true && sudo docker rm microservice_list_catalog || true
            sudo docker stop microservice_delete_catalog || true && sudo docker rm microservice_delete_catalog || true

            mkdir -p src
            echo "RDS_HOST=${{ secrets.RDS_HOST }}" > src/.env
            echo "RDS_PORT=${{ secrets.RDS_PORT }}" >> src/.env
            echo "RDS_DATABASE=${{ secrets.RDS_DATABASE }}" >> src/.env
            echo "RDS_USER=${{ secrets.RDS_USER }}" >> src/.env
            echo "RDS_PASSWORD=${{ secrets.RDS_PASSWORD }}" >> src/.env

            cat src/.env

            echo "Ejecutando microservicios book_catalog..."
            sudo docker run -d --name microservice_registre_catalog --env-file src/.env -p 3001:3001 ${{ secrets.DOCKER_USERNAME }}/microservice_registre_catalog:latest
            sudo docker run -d --name microservice_update_catalog --env-file src/.env -p 3003:3003 ${{ secrets.DOCKER_USERNAME }}/microservice_update_catalog:latest
            sudo docker run -d --name microservice_list_catalog --env-file src/.env -p 3002:3002 ${{ secrets.DOCKER_USERNAME }}/microservice_list_catalog:latest
            sudo docker run -d --name microservice_delete_catalog --env-file src/.env -p 3004:3004 ${{ secrets.DOCKER_USERNAME }}/microservice_delete_catalog:latest

            sudo docker ps -a
            echo "Deployment of book_catalog completed."

  deploy-reservation-management:
    needs: build-and-push
    runs-on: ubuntu-latest
    steps:
      - name: SSH into EC2 Reservation Management and deploy containers
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ secrets.EC2_RESERVATION_IP }}
          username: ubuntu
          key: ${{ secrets.RESERVATION_KEY }}
          script: |
            if ! command -v docker &> /dev/null; then
              echo "Docker no está instalado. Instalando..."
              sudo apt update && sudo apt install -y docker.io
            fi
            sudo systemctl enable --now docker

            echo "Descargando imágenes..."
            sudo docker pull ${{ secrets.DOCKER_USERNAME }}/microservice_register_reservation:latest
            sudo docker pull ${{ secrets.DOCKER_USERNAME }}/microservice_update_reservation:latest
            sudo docker pull ${{ secrets.DOCKER_USERNAME }}/microservice_list_reservation:latest
            sudo docker pull ${{ secrets.DOCKER_USERNAME }}/microservice_delete_reservation:latest

            sudo docker stop microservice_register_reservation || true && sudo docker rm microservice_register_reservation || true
            sudo docker stop microservice_update_reservation || true && sudo docker rm microservice_update_reservation || true
            sudo docker stop microservice_list_reservation || true && sudo docker rm microservice_list_reservation || true
            sudo docker stop microservice_delete_reservation || true && sudo docker rm microservice_delete_reservation || true

            mkdir -p src
            echo "RDS_HOST=${{ secrets.RDS_HOST }}" > src/.env
            echo "RDS_PORT=${{ secrets.RDS_PORT }}" >> src/.env
            echo "RDS_DATABASE=${{ secrets.RDS_DATABASE }}" >> src/.env
            echo "RDS_USER=${{ secrets.RDS_USER }}" >> src/.env
            echo "RDS_PASSWORD=${{ secrets.RDS_PASSWORD }}" >> src/.env

            cat src/.env

            echo "Ejecutando microservicios reservation_management..."
            sudo docker run -d --name microservice_register_reservation --env-file src/.env -p 7000:7000 ${{ secrets.DOCKER_USERNAME }}/microservice_register_reservation:latest
            sudo docker run -d --name microservice_update_reservation --env-file src/.env -p 7003:7003 ${{ secrets.DOCKER_USERNAME }}/microservice_update_reservation:latest
            sudo docker run -d --name microservice_list_reservation --env-file src/.env -p 7001:7001 ${{ secrets.DOCKER_USERNAME }}/microservice_list_reservation:latest
            sudo docker run -d --name microservice_delete_reservation --env-file src/.env -p 7002:7002 ${{ secrets.DOCKER_USERNAME }}/microservice_delete_reservation:latest

            sudo docker ps -a
            echo "Deployment of reservation_management completed."

  deploy-users:
    needs: build-and-push
    runs-on: ubuntu-latest
    steps:
      - name: SSH into EC2 Users and deploy containers
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ secrets.EC2_USERS_IP }}
          username: ubuntu
          key: ${{ secrets.USERS_KEY }}
          script: |
            if ! command -v docker &> /dev/null; then
              echo "Docker no está instalado. Instalando..."
              sudo apt update && sudo apt install -y docker.io
            fi
            sudo systemctl enable --now docker

            echo "Descargando imágenes..."
            sudo docker pull ${{ secrets.DOCKER_USERNAME }}/microservice_register_user:latest
            sudo docker pull ${{ secrets.DOCKER_USERNAME }}/microservice_update_user:latest
            sudo docker pull ${{ secrets.DOCKER_USERNAME }}/microservice_list_user:latest
            sudo docker pull ${{ secrets.DOCKER_USERNAME }}/microservice_delete_user:latest

            sudo docker stop microservice_register_user || true && sudo docker rm microservice_register_user || true
            sudo docker stop microservice_update_user || true && sudo docker rm microservice_update_user || true
            sudo docker stop microservice_list_user || true && sudo docker rm microservice_list_user || true
            sudo docker stop microservice_delete_user || true && sudo docker rm microservice_delete_user || true

            mkdir -p src
            echo "RDS_HOST=${{ secrets.RDS_HOST }}" > src/.env
            echo "RDS_PORT=${{ secrets.RDS_PORT }}" >> src/.env
            echo "RDS_DATABASE=${{ secrets.RDS_DATABASE }}" >> src/.env
            echo "RDS_USER=${{ secrets.RDS_USER }}" >> src/.env
            echo "RDS_PASSWORD=${{ secrets.RDS_PASSWORD }}" >> src/.env

            cat src/.env

            echo "Ejecutando microservicios users..."
            sudo docker run -d --name microservice_register_user --env-file src/.env -p 5000:5000 ${{ secrets.DOCKER_USERNAME }}/microservice_register_user:latest
            sudo docker run -d --name microservice_update_user --env-file src/.env -p 5003:5003 ${{ secrets.DOCKER_USERNAME }}/microservice_update_user:latest
            sudo docker run -d --name microservice_list_user --env-file src/.env -p 5001:5001 ${{ secrets.DOCKER_USERNAME }}/microservice_list_user:latest
            sudo docker run -d --name microservice_delete_user --env-file src/.env -p 5002:5002 ${{ secrets.DOCKER_USERNAME }}/microservice_delete_user:latest

            sudo docker ps -a
            echo "Deployment of users completed."
